

#undef COUNTER_A_NEW_VALUE
#undef COUNTER_A_DIGIT_TEMP_4
#undef COUNTER_A_DIGIT_TEMP_3
#undef COUNTER_A_DIGIT_TEMP_2
#undef COUNTER_A_DIGIT_TEMP_1

#define COUNTER_A_NEW_VALUE (COUNTER_A + 0x1)

#if COUNTER_A_NEW_VALUE >> 12 == 0
#	define COUNTER_A_DIGIT_TEMP_4 0
#elif COUNTER_A_NEW_VALUE >> 12 == 1
#	define COUNTER_A_DIGIT_TEMP_4 1
#elif COUNTER_A_NEW_VALUE >> 12 == 2
#	define COUNTER_A_DIGIT_TEMP_4 2
#elif COUNTER_A_NEW_VALUE >> 12 == 3
#	define COUNTER_A_DIGIT_TEMP_4 3
#elif COUNTER_A_NEW_VALUE >> 12 == 4
#	define COUNTER_A_DIGIT_TEMP_4 4
#elif COUNTER_A_NEW_VALUE >> 12 == 5
#	define COUNTER_A_DIGIT_TEMP_4 5
#elif COUNTER_A_NEW_VALUE >> 12 == 6
#	define COUNTER_A_DIGIT_TEMP_4 6
#elif COUNTER_A_NEW_VALUE >> 12 == 7
#	define COUNTER_A_DIGIT_TEMP_4 7
#elif COUNTER_A_NEW_VALUE >> 12 == 8
#	define COUNTER_A_DIGIT_TEMP_4 8
#elif COUNTER_A_NEW_VALUE >> 12 == 9
#	define COUNTER_A_DIGIT_TEMP_4 9
#elif COUNTER_A_NEW_VALUE >> 12 == 10
#	define COUNTER_A_DIGIT_TEMP_4 0xa
#elif COUNTER_A_NEW_VALUE >> 12 == 11
#	define COUNTER_A_DIGIT_TEMP_4 0xb
#elif COUNTER_A_NEW_VALUE >> 12 == 12
#	define COUNTER_A_DIGIT_TEMP_4 0xc
#elif COUNTER_A_NEW_VALUE >> 12 == 13
#	define COUNTER_A_DIGIT_TEMP_4 0xd
#elif COUNTER_A_NEW_VALUE >> 12 == 14
#	define COUNTER_A_DIGIT_TEMP_4 0xe
#elif COUNTER_A_NEW_VALUE >> 12 == 15
#	define COUNTER_A_DIGIT_TEMP_4 0xf
#endif



#if (COUNTER_A_NEW_VALUE >> 8)%16 == 0
#	define COUNTER_A_DIGIT_TEMP_3 0
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 1
#	define COUNTER_A_DIGIT_TEMP_3 1
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 2
#	define COUNTER_A_DIGIT_TEMP_3 2
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 3
#	define COUNTER_A_DIGIT_TEMP_3 3
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 4
#	define COUNTER_A_DIGIT_TEMP_3 4
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 5
#	define COUNTER_A_DIGIT_TEMP_3 5
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 6
#	define COUNTER_A_DIGIT_TEMP_3 6
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 7
#	define COUNTER_A_DIGIT_TEMP_3 7
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 8
#	define COUNTER_A_DIGIT_TEMP_3 8
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 9
#	define COUNTER_A_DIGIT_TEMP_3 9
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 10
#	define COUNTER_A_DIGIT_TEMP_3 0xa
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 11
#	define COUNTER_A_DIGIT_TEMP_3 0xb
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 12
#	define COUNTER_A_DIGIT_TEMP_3 0xc
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 13
#	define COUNTER_A_DIGIT_TEMP_3 0xd
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 14
#	define COUNTER_A_DIGIT_TEMP_3 0xe
#elif (COUNTER_A_NEW_VALUE >> 8)%16 == 15
#	define COUNTER_A_DIGIT_TEMP_3 0xf
#endif


#if (COUNTER_A_NEW_VALUE >> 4)%16 == 0
#	define COUNTER_A_DIGIT_TEMP_2 0
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 1
#	define COUNTER_A_DIGIT_TEMP_2 1
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 2
#	define COUNTER_A_DIGIT_TEMP_2 2
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 3
#	define COUNTER_A_DIGIT_TEMP_2 3
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 4
#	define COUNTER_A_DIGIT_TEMP_2 4
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 5
#	define COUNTER_A_DIGIT_TEMP_2 5
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 6
#	define COUNTER_A_DIGIT_TEMP_2 6
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 7
#	define COUNTER_A_DIGIT_TEMP_2 7
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 8
#	define COUNTER_A_DIGIT_TEMP_2 8
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 9
#	define COUNTER_A_DIGIT_TEMP_2 9
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 10
#	define COUNTER_A_DIGIT_TEMP_2 0xa
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 11
#	define COUNTER_A_DIGIT_TEMP_2 0xb
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 12
#	define COUNTER_A_DIGIT_TEMP_2 0xc
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 13
#	define COUNTER_A_DIGIT_TEMP_2 0xd
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 14
#	define COUNTER_A_DIGIT_TEMP_2 0xe
#elif (COUNTER_A_NEW_VALUE >> 4)%16 == 15
#	define COUNTER_A_DIGIT_TEMP_2 0xf
#endif

#if (COUNTER_A_NEW_VALUE)%16 == 0
#	define COUNTER_A_DIGIT_TEMP_1 0
#elif (COUNTER_A_NEW_VALUE)%16 == 1
#	define COUNTER_A_DIGIT_TEMP_1 1
#elif (COUNTER_A_NEW_VALUE)%16 == 2
#	define COUNTER_A_DIGIT_TEMP_1 2
#elif (COUNTER_A_NEW_VALUE)%16 == 3
#	define COUNTER_A_DIGIT_TEMP_1 3
#elif (COUNTER_A_NEW_VALUE)%16 == 4
#	define COUNTER_A_DIGIT_TEMP_1 4
#elif (COUNTER_A_NEW_VALUE)%16 == 5
#	define COUNTER_A_DIGIT_TEMP_1 5
#elif (COUNTER_A_NEW_VALUE)%16 == 6
#	define COUNTER_A_DIGIT_TEMP_1 6
#elif (COUNTER_A_NEW_VALUE)%16 == 7
#	define COUNTER_A_DIGIT_TEMP_1 7
#elif (COUNTER_A_NEW_VALUE)%16 == 8
#	define COUNTER_A_DIGIT_TEMP_1 8
#elif (COUNTER_A_NEW_VALUE)%16 == 9
#	define COUNTER_A_DIGIT_TEMP_1 9
#elif (COUNTER_A_NEW_VALUE)%16 == 10
#	define COUNTER_A_DIGIT_TEMP_1 0xa
#elif (COUNTER_A_NEW_VALUE)%16 == 11
#	define COUNTER_A_DIGIT_TEMP_1 0xb
#elif (COUNTER_A_NEW_VALUE)%16 == 12
#	define COUNTER_A_DIGIT_TEMP_1 0xc
#elif (COUNTER_A_NEW_VALUE)%16 == 13
#	define COUNTER_A_DIGIT_TEMP_1 0xd
#elif (COUNTER_A_NEW_VALUE)%16 == 14
#	define COUNTER_A_DIGIT_TEMP_1 0xe
#elif (COUNTER_A_NEW_VALUE)%16 == 15
#	define COUNTER_A_DIGIT_TEMP_1 0xf
#endif



#undef COUNTER_A_DIGIT_1
#undef COUNTER_A_DIGIT_2
#undef COUNTER_A_DIGIT_3
#undef COUNTER_A_DIGIT_4

#if COUNTER_A_DIGIT_TEMP_1 == 0
#	define COUNTER_A_DIGIT_1 0
#elif COUNTER_A_DIGIT_TEMP_1 == 1
#	define COUNTER_A_DIGIT_1 1
#elif COUNTER_A_DIGIT_TEMP_1 == 2
#	define COUNTER_A_DIGIT_1 2
#elif COUNTER_A_DIGIT_TEMP_1 == 3
#	define COUNTER_A_DIGIT_1 3
#elif COUNTER_A_DIGIT_TEMP_1 == 4
#	define COUNTER_A_DIGIT_1 4
#elif COUNTER_A_DIGIT_TEMP_1 == 5
#	define COUNTER_A_DIGIT_1 5
#elif COUNTER_A_DIGIT_TEMP_1 == 6
#	define COUNTER_A_DIGIT_1 6
#elif COUNTER_A_DIGIT_TEMP_1 == 7
#	define COUNTER_A_DIGIT_1 7
#elif COUNTER_A_DIGIT_TEMP_1 == 8
#	define COUNTER_A_DIGIT_1 8
#elif COUNTER_A_DIGIT_TEMP_1 == 9
#	define COUNTER_A_DIGIT_1 9
#elif COUNTER_A_DIGIT_TEMP_1 == 0xa
#	define COUNTER_A_DIGIT_1 a
#elif COUNTER_A_DIGIT_TEMP_1 == 0xb
#	define COUNTER_A_DIGIT_1 b
#elif COUNTER_A_DIGIT_TEMP_1 == 0xc
#	define COUNTER_A_DIGIT_1 c
#elif COUNTER_A_DIGIT_TEMP_1 == 0xd
#	define COUNTER_A_DIGIT_1 d
#elif COUNTER_A_DIGIT_TEMP_1 == 0xe
#	define COUNTER_A_DIGIT_1 e
#elif COUNTER_A_DIGIT_TEMP_1 == 0xf
#	define COUNTER_A_DIGIT_1 f
#endif

#if COUNTER_A_DIGIT_TEMP_2 == 0
#	define COUNTER_A_DIGIT_2 0
#elif COUNTER_A_DIGIT_TEMP_2 == 1
#	define COUNTER_A_DIGIT_2 1
#elif COUNTER_A_DIGIT_TEMP_2 == 2
#	define COUNTER_A_DIGIT_2 2
#elif COUNTER_A_DIGIT_TEMP_2 == 3
#	define COUNTER_A_DIGIT_2 3
#elif COUNTER_A_DIGIT_TEMP_2 == 4
#	define COUNTER_A_DIGIT_2 4
#elif COUNTER_A_DIGIT_TEMP_2 == 5
#	define COUNTER_A_DIGIT_2 5
#elif COUNTER_A_DIGIT_TEMP_2 == 6
#	define COUNTER_A_DIGIT_2 6
#elif COUNTER_A_DIGIT_TEMP_2 == 7
#	define COUNTER_A_DIGIT_2 7
#elif COUNTER_A_DIGIT_TEMP_2 == 8
#	define COUNTER_A_DIGIT_2 8
#elif COUNTER_A_DIGIT_TEMP_2 == 9
#	define COUNTER_A_DIGIT_2 9
#elif COUNTER_A_DIGIT_TEMP_2 == 0xa
#	define COUNTER_A_DIGIT_2 a
#elif COUNTER_A_DIGIT_TEMP_2 == 0xb
#	define COUNTER_A_DIGIT_2 b
#elif COUNTER_A_DIGIT_TEMP_2 == 0xc
#	define COUNTER_A_DIGIT_2 c
#elif COUNTER_A_DIGIT_TEMP_2 == 0xd
#	define COUNTER_A_DIGIT_2 d
#elif COUNTER_A_DIGIT_TEMP_2 == 0xe
#	define COUNTER_A_DIGIT_2 e
#elif COUNTER_A_DIGIT_TEMP_2 == 0xf
#	define COUNTER_A_DIGIT_2 f
#endif



#if COUNTER_A_DIGIT_TEMP_3 == 0
#	define COUNTER_A_DIGIT_3 0
#elif COUNTER_A_DIGIT_TEMP_3 == 1
#	define COUNTER_A_DIGIT_3 1
#elif COUNTER_A_DIGIT_TEMP_3 == 2
#	define COUNTER_A_DIGIT_3 2
#elif COUNTER_A_DIGIT_TEMP_3 == 3
#	define COUNTER_A_DIGIT_3 3
#elif COUNTER_A_DIGIT_TEMP_3 == 4
#	define COUNTER_A_DIGIT_3 4
#elif COUNTER_A_DIGIT_TEMP_3 == 5
#	define COUNTER_A_DIGIT_3 5
#elif COUNTER_A_DIGIT_TEMP_3 == 6
#	define COUNTER_A_DIGIT_3 6
#elif COUNTER_A_DIGIT_TEMP_3 == 7
#	define COUNTER_A_DIGIT_3 7
#elif COUNTER_A_DIGIT_TEMP_3 == 8
#	define COUNTER_A_DIGIT_3 8
#elif COUNTER_A_DIGIT_TEMP_3 == 9
#	define COUNTER_A_DIGIT_3 9
#elif COUNTER_A_DIGIT_TEMP_3 == 0xa
#	define COUNTER_A_DIGIT_3 a
#elif COUNTER_A_DIGIT_TEMP_3 == 0xb
#	define COUNTER_A_DIGIT_3 b
#elif COUNTER_A_DIGIT_TEMP_3 == 0xc
#	define COUNTER_A_DIGIT_3 c
#elif COUNTER_A_DIGIT_TEMP_3 == 0xd
#	define COUNTER_A_DIGIT_3 d
#elif COUNTER_A_DIGIT_TEMP_3 == 0xe
#	define COUNTER_A_DIGIT_3 e
#elif COUNTER_A_DIGIT_TEMP_3 == 0xf
#	define COUNTER_A_DIGIT_3 f
#endif


#if COUNTER_A_DIGIT_TEMP_4 == 0
#	define COUNTER_A_DIGIT_4 0
#elif COUNTER_A_DIGIT_TEMP_4 == 1
#	define COUNTER_A_DIGIT_4 1
#elif COUNTER_A_DIGIT_TEMP_4 == 2
#	define COUNTER_A_DIGIT_4 2
#elif COUNTER_A_DIGIT_TEMP_4 == 3
#	define COUNTER_A_DIGIT_4 3
#elif COUNTER_A_DIGIT_TEMP_4 == 4
#	define COUNTER_A_DIGIT_4 4
#elif COUNTER_A_DIGIT_TEMP_4 == 5
#	define COUNTER_A_DIGIT_4 5
#elif COUNTER_A_DIGIT_TEMP_4 == 6
#	define COUNTER_A_DIGIT_4 6
#elif COUNTER_A_DIGIT_TEMP_4 == 7
#	define COUNTER_A_DIGIT_4 7
#elif COUNTER_A_DIGIT_TEMP_4 == 8
#	define COUNTER_A_DIGIT_4 8
#elif COUNTER_A_DIGIT_TEMP_4 == 9
#	define COUNTER_A_DIGIT_4 9
#elif COUNTER_A_DIGIT_TEMP_4 == 0xa
#	define COUNTER_A_DIGIT_4 a
#elif COUNTER_A_DIGIT_TEMP_4 == 0xb
#	define COUNTER_A_DIGIT_4 b
#elif COUNTER_A_DIGIT_TEMP_4 == 0xc
#	define COUNTER_A_DIGIT_4 c
#elif COUNTER_A_DIGIT_TEMP_4 == 0xd
#	define COUNTER_A_DIGIT_4 d
#elif COUNTER_A_DIGIT_TEMP_4 == 0xe
#	define COUNTER_A_DIGIT_4 e
#elif COUNTER_A_DIGIT_TEMP_4 == 0xf
#	define COUNTER_A_DIGIT_4 f
#endif


#undef COUNTER_A

#define COUNTER_A COUNTER_CONCAT(COUNTER_A_DIGIT_4,COUNTER_A_DIGIT_3,COUNTER_A_DIGIT_2,COUNTER_A_DIGIT_1)
